package com.marcoTorres.studentsystem.model;
// The Kakarta Persistence API, is a specification for object-relational mapping
// in java. It defines a set of APIs and annotations for mapping Java Objects to relational
// database tables and enables developers to perform database operations using
// object-oriented paradigms

// The Entity annotation is a core annotation in the JP API. it is used to mark
// Java class as an entity, indicating that instance of the class will be persisted to a relational
// database
import jakarta.persistence.Entity;
// The GeneratedValue annotation is used in conjunction with the @Id annotation to specify
// how the primary key values for entities are automatically generated by the persistence provider
import jakarta.persistence.GeneratedValue;
// The GenerationType enumeration provides the options for specifying how the
// primary key values should be generated.
// An example would be GenerationType.IDENTITY: here the primary key values
// are generated by an identity column in the database. This strategy is
// typically used in databases that support auto incrementing columns
import jakarta.persistence.GenerationType;
// The ID annotation is used to maker a field as the primary key of an entity
// in a relational database
import jakarta.persistence.Id;

@Entity
public class Student {

//  this will make it the primary key
  @Id
//  this will make the id auto incremented as well
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;
  private String name;
  private String address;

  public Student() {
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }
}
